"""agrego token discogs usuario

Revision ID: 7e749b207e71
Revises: 7e5f630a496e
Create Date: 2026-09-22 23:09:38.042511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e749b207e71'
down_revision = '7e5f630a496e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discogs_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('discogs_token')

    # ### end Alembic commands ###
